version: '3.4'

services:
  biblio.webapi:
    image: ${DOCKER_REGISTRY-}bibliowebapi
    container_name: BiblioTech
    build:
      context: .
      dockerfile: src/Biblio.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:80"
    restart: always
    environment:
      DBHOST: database
      ASPNETCORE_ENVIRONMENT: Development

  database:
    image: postgres:15.3
    container_name: BiblioTechDB
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - db-volume:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bibliotech

volumes:
  db-volume:  
